### PR TITLE
Several formatting changes

### PR DESCRIPTION
**Pull request by ochaloup**
As reading I made some formatting changes to enhance the text.

For some notes about content, having already in my mind, I need to read at least once again.

### CODE REVIEW

**Comment by mmusgrov** [comment]
Would you mind raising it against the open PR on the eclipse repo: https://github.com/eclipse/microprofile-sandbox/pull/2

**Comment by ochaloup** [comment]
@mmusgrov sure, no problem. I will close this one and open a new one. This `jbosstm` repo will not be used for PR anymore, right?

**Comment by ochaloup** [comment]
@mmusgrov Tom approved the changes so I merged that but now I realized that it will not go to your pr to eclipse (eclipse#2) as it's pointed from `master` not from this `0009-LRA` branch. Would not be ok to create PR to `master` branch and you will check and merge it and it will be shown in the eclipse one?

**Comment by mmusgrov** [comment]
@ochaloup yes that is the correct strategy for all future LRA/SRA spec updates.

**Pull request merged**
